#! /bin/sh
PLAYER=/tmp/playerctlname
pgrep -x mocp
if [ $? -eq 1 ]
then
	if [ $(playerctl -l | wc -l) = 1 ]
		then
			playerctl previous
	else
		if [ ! -f "$PLAYER" ]; then
			plid=$(echo -e "$(playerctl -l)" | rofi -dmenu -p "Select Player")
			playerctl -p $plid previous
			if [ ! -z "$plid" ];then
				echo $plid >> $PLAYER
			fi
		else
			playerctl -p $(head -n 1 $PLAYER) previous
		fi
	fi
else
	mocp -r
fi
