#!/bin/sh
PLAYER=/tmp/playerctlname
pgrep -x mocp
if [ $? -eq 1 ]
then
	if [ $(playerctl -l | wc -l) = 1 ]
		then
			playerctl next 
	else
		if [ ! -f "$PLAYER" ]; then
			plid=$(echo -e "$(playerctl -l)" | rofi -dmenu)
			playerctl -p $plid next
			if [ ! -z "$plid" ];then
				echo $plid >> $PLAYER
			fi
		else
			playerctl -p $(head -n 1 $PLAYER) next
		fi
	fi
else
	mocp -f
fi
