#! /bin/sh
PLAYER=/tmp/playerctlname
pgrep -x mocp
if [ $? -eq 1 ]
then
	if [ $(playerctl -l | wc -l) = 1 ]
		then
			playerctl play-pause
	else
		if [ ! -f "$PLAYER" ]; then
			plid=$(echo -e "$(playerctl -l)" | rofi -dmenu)
			playerctl -p $plid play-pause
			echo $plid >> $PLAYER
		else
			playerctl -p $(head -n 1 $PLAYER) play-pause
		fi
	fi
else
	mocp -G
fi
