#! /bin/sh
pgrep -x mocp
if [ $? -eq 1 ]
then
	if [ $(playerctl -l | wc -l) = 1 ]
		then
			playerctl previous
	else
		playerctl -p $(echo -e "$(playerctl -l)" | rofi -dmenu) previous
	fi
else
	mocp -r
fi
