#! /bin/sh
PLAYER=/tmp/playerctlname
pgrep -x mocp
if [ $? -eq 1 ]
then
	if [ $(playerctl -l | wc -l) = 1 ]
		then
			playerctl previous
	else
		if [ ! -f "$PLAYER" ]; then
			plid=$(echo -e "$(playerctl -l)" | rofi -dmenu)
			playerctl -p $plid previous
			echo $plid >> $PLAYER
		else
			playerid=$(head -n 1 $PLAYER)
			playerctl -p $playerid previous
		fi
	fi
else
	mocp -r
fi
