#!/bin/sh
options="Jazz24\nJazz24-low\nSomaFM-SecretAgent\nTSFJazz\nCinemix\nJazzFM\nDRP8-Jazz\nJazzFM91\nRadioSwissClassic\nRadioSwissJazz\nXO-FM\nRelaxFM\nJazzRadioBlues"
chosen="$(echo -e "$options" | rofi -dmenu -i -p "Select Radio to play : ")"
case $chosen in
				Jazz24)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/jazz24.pls'
								;;
				Jazz24-low)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/jazz24low.pls'
								;;
				SomaFM-SecretAgent)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/secretagent130.pls'
								;;
				TSFJazz)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/tsfjazz.pls'
								;;
				Cinemix)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/cinemix.pls'
								;;
				JazzFM)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/jazzfm.pls'
								;;
				DRP8-Jazz)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/drp8.pls'
								;;
				JazzFM91)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/jazz91.pls'
								;;
				RadioSwissClassic)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/rsc.pls'
								;;
				RadioSwissJazz)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/rsj.pls'
								;;
				XO-FM)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/xo.pls'
								;;
				RelaxFM)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/relax.pls'
								;;
				JazzRadioBlues)
								sh -c 'echo $$ >> /tmp/radio.pid; exec mpv ~/.local/share/radio/jrb.pls'
								;;
				*)
								exit
								;;
esac

