#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

# source colors generated using pywal
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         3
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config honor_size_hints	 false

#### Applications to autostart
##start picom
picom --experimental-backends -b &

# wallpaper
habak -ms ~/.cache/wallpaper.jpg

##numlock state
numlockx &

##get rid of the rat when not needed
unclutter &

##touchpad gestures
libinput-gestures-setup start &

##restore wal colorscheme
wal -R &

##launch polybar
polybar main &

wmname LG3D &

##turn on vim speedmode
xmodmap ~/.config/scripts/speedswapperon &

bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a aft-linux-qt state=floating
bspc rule -a feh state=floating
bspc rule -a Otpclient:otpclient state=floating
bspc rule -a LibreWolf:Toolkit sticky=on state=floating
bspc rule -a VirtualBoxVM:VirtualBoxVM desktop='8'
bspc rule -a Zathura:\* state=fullscreen
bspc rule -a Galculator:galculator state=floating
bspc rule -a 'jetbrains-studio:sun-awt-X11-XWindowPeer' manage=off
