#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

# source colors generated using pywal
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         3
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config honor_size_hints	 false

#### Applications to autostart
##start picom
picom -b &

# wallpaper
habak -ms ~/.cache/wallpaper.jpg

##start urxvt daemon
urxvtd --quiet --opendisplay --fork &

##numlock state
numlockx &

##get rid of the rat when not needed
unclutter &

##touchpad gestures
libinput-gestures-setup start &

##restore wal colorscheme
wal -R &

##launch polybar
polybar main &

##turn on vim speedmode
xmodmap ~/.config/scripts/speedswapperon &

##notify when low battery
sh ~/.config/scripts/battery_check &

bspc rule -a firefox desktop='^3'
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a aft-linux-qt state=floating
bspc rule -a feh state=floating
bspc rule -a 2.3.0 state=floating
bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a java-lang-Thread:sun-awt-X11-XWindowPeer state=floating desktop='^2'
